apiVersion: v1
kind: Secret
metadata:
  name: wedding-secret
  namespace: livekit
type: Opaque
stringData:
  YANDEX_CLIENT_ID: "your_client_id_here"
  YANDEX_CLIENT_SECRET: "your_client_secret_here"
  YANDEX_REFRESH_TOKEN: ""
